id: I6A988C00
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T01:50:36+00:00'
last_modified: '2022-06-08T08:39:47.517739+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG01507
  title: དྲུག་ཅུ་མའི་རྩ་ཚིག་ཞ་ལུ་པ་ཆེན་པོའི་མཛད་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedSealed
  restrictedInChina: false
  base:
    C69C:
      image_group_id: I00KG02818
      title: ''
      total_pages: 8
      order: 1
      base_file: C69C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
