id: P006852
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W00KG01507
  title: དྲུག་ཅུ་མའི་རྩ་ཚིག་ཞ་ལུ་པ་ཆེན་པོའི་མཛད་པ
  author: ''
  volumes:
    a9ba3136959e4214931437867bb02b98:
      image_group_id: I00KG02818
      title: ''
      volume_number: 1
      total_pages: 8
      base_file: v001.txt
